### ISSUE TITLE
[Bug]: mambaforge install fails after update, executable not found

### ISSUE THREAD

**Issue by c-ortbauer** [ScoopInstaller/Extras#10420]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mambaforge

### Expected/Current Behaviour

`scoop install mambaforge` should install without error

### Steps to Reproduce

```console
PS C:\Users\orc> scoop install mambaforge
Installing 'mambaforge' (22.11.1-2) [64bit] from extras bucket
Loading Mambaforge-22.11.1-2-Windows-x86_64.exe from cache
Checking hash of Mambaforge-22.11.1-2-Windows-x86_64.exe ... ok.
Running installer script...
Linking ~\scoop\apps\mambaforge\current => ~\scoop\apps\mambaforge\22.11.1-2
Creating shim for 'python'.
Creating shim for 'pythonw'.
Can't shim 'pythonw.exe': File doesn't exist.
PS C:\Users\orc>
```

### Possible Solution

From a bit of testing it seems to me like the new installer (22.11.1-2) only installs if the target directory is empty. 
As the installer itself is located in the target dir, nothing is installed.
The old installer (22.9.0-3) does not care if the directory is not empty.

I don't know what the best way to fix this is. Maybe move the downloaded installer to a temporary director pre-install?

### Scoop and Buckets Version

```console
PS C:\Users\orc> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
200c0942c (HEAD -> master, origin/master, origin/HEAD) tableplus: Update to version 5.2.8.220

'main' bucket:
24ed63a21 (HEAD -> master, origin/master, origin/HEAD) sentinel: Update to version 0.19.3
```

### Scoop Config

```console
PS C:\Users\orc> scoop config

use_lessmsi last_update                       scoop_branch scoop_repo
----------- -----------                       ------------ ----------
       True 2023-02-03T06:59:30.2261925+01:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\orc> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by drewbitt** [comment]
+1. The upgrade lost me my conda executable

**Comment by Direct-A** [comment]
I've meet the same bug.
My `C:\Users\xxx\scoop\apps\mambaforge\current` folder and `C:\Users\xxx\scoop\apps\mambaforge\22.11.1-2` folder are both empty

**Comment by hmaarrfk** [comment]
Jaime has been doing most of the debugging. But their comments in 
- https://github.com/conda-forge/miniforge/issues/421#issuecomment-1421037380
- https://github.com/conda-forge/miniforge/issues/421#issuecomment-1421115066

suggest (as is my understsanding) that either: 

- Allowing a user to pass command line arguments can help configure the mambaforge installation.
- Using `/AddToPath=1` in scoop would restore the previous behavior.

Help in understand *where* mambaforge is installed would be great for as it might allow users to manually add conda to their path afterward if neither of the options above are OK.

**Comment by elovelan** [comment]
Update: the issue is related to an issue with Scoop's default behavior of copying the installer to the install directory, which the Mambaforge installer no longer supports. @chortbauer's (aka @c-ortbauer) PR #10457 works around this issue for the time being until a way can be found to either update [constructor](https://github.com/conda/constructor) to allow this again or get some assistance from the Scoop maintainers about other workarounds.

**Comment by elovelan** [comment]
Note: if you'd like to fix a broken installation, you can either revert to the last working version or use the PR's fixed version.

Do the following to install the last working version. Note that this puts Scoop into a state where it thinks the latest version never changes so you'll need to run `scoop uninstall mambaforge; scoop install mambaforge` once the fix is available:

```sh
scoop install mambaforge@22.9.0-3
```

If you'd like to use the fixed version change to the directory where your extras bucket is installed (typically `~\scoop\buckets\extras`). This is just a git repo, so we can use the following commands to switch to the PR branch and install from there. Note that running `scoop update` first is optional, but it can cause issues if it tries to run an update before installing from a different branch/ref!

From PowerShell or Bash, etc:

```shell
pushd ~\scoop\buckets\extras
```

From cmd:

```cmd
pushd %USERPROFILE%\scoop\buckets\extras
```

then:

```shell
scoop update
git fetch origin pull/10457/head
git switch --detach FETCH_HEAD
scoop install mambaforge
git switch master
popd
```
