### ISSUE TITLE
[Bug]: Remove KeenWrite

### ISSUE THREAD

**Issue by DaveJarvis** [ScoopInstaller/Extras#10893]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

KeenWrite

### Expected/Current Behaviour

Please remove KeenWrite from Scoop, thank you.

### Steps to Reproduce

```console
Remove KeenWrite.
```

### Possible Solution

Remove KeenWrite.

### Scoop and Buckets Version

```console
Remove KeenWrite.
```

### Scoop Config

```console
Remove KeenWrite.
```

### PowerShell Version

```console
Remove KeenWrite.
```

### Additional Softwares

Remove KeenWrite.

**Comment by HUMORCE** [comment]
May I know why you want to remove it from this bucket?

**Comment by Zliced13** [comment]
> If scoop could guarantee that no pages related to KeenWrite would ever go stale _and_ scoop always retrieves the latest version directly from the GitHub releases page, then that would be agreeable.
>
Scoop always retrieves the latest version of the app, as seen right here in this commit https://github.com/ScoopInstaller/Extras/commit/45d88d218903c2c592b7b598f3fa06c52ce1d8bf.

**Comment by leumasme** [comment]
> The page at https://bjansen.github.io/scoop-apps/extras/keenwrite/ has gone stale.

This page only updates manually and is not really used anymore as [the official scoop site](https://scoop.sh/#/apps?q=keenwrite&s=0&d=1&o=true) also shows package information now.
Considering this, removing your application from scoop also wouldnt remove it from that site until someone updates it.
The version of your project currently installable through scoop is not correctly represented there, its currently actually "3.2.0".
This is also automatically updated whenever you push a release to github. The official scoop site is updated only a few hours later with the latest package version.

> I prefer to keep downloads centralized (i.e., via GitHub's release page) so that I can track downloads.

Scoop only distributes manifests that instruct the scoop installer on how to install your application. No download files are provided by scoop, they are all still downloaded from your github releases page. The current url is:
"https://github.com/DaveJarvis/keenwrite/releases/download/3.2.0/keenwrite.exe#/dl.7z"
Note that this is the direct url to the file from your github releases file. I do not know how exactly github releases tracks downloads, so I dont know if downloading directly from the URL without visiting the releases page will still increase your download counter.

> As a minor quip, KeenWrite has no "installer" or installation process per se. [...] I fail to see what scoop offers except saving a few keystrokes.

Thank you for making portable software without unnecessary installers. Here are some advantages of installing software via scoop:
- Centralized place to install, uninstall and update software (just ask linux users how awesome package managers are!)
- No need to go searching for the download link (notably also protects from falling for fake/malware downloads, see for example malicious google search ads targetting people who want to download VLC)
- Automatically adding relevant files to the PATH if they have a CLI and to the Start Menu if they have a GUI (and ONLY the relevant files, no more cluttered path because you added the whole application path)
- Software doesn't need to be manually updated (or started if it has an automatic updater)

**Comment by DaveJarvis** [comment]
> Scoop always retrieves the latest version of the app, as seen right here in this commit https://github.com/ScoopInstaller/Extras/commit/45d88d218903c2c592b7b598f3fa06c52ce1d8bf.

From my perspective, a scoop-related page has gone stale (regardless of who made the page), meaning there is no guarantees that scoop-related pages are always up-to-date.

Please remove KeenWrite from scoop.

Thank you.

**Comment by HUMORCE** [comment]
I removed it in accordance with this item in the licence:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

When you choose the BSD 2-Clause License, you (the author) cannot prohibit anyone from distribution, when all conditions in license are met.

**Comment by chawyehsu** [comment]
The only convincing excuse I can see here for it is to keep it centralized arbitrarily for stats tracking purposes, anything else claimed here makes no sence. Removing the manifest from THIS repo does NOT fix the claimed problem of `a scoop-related page has gone stale` when the actual page lacking of maintenance is not offline. Sir you are forbidding Scoop users from using your nice software. And if you do worry about users getting outdated version of the software, you should DMCA or sth else to take down that page, instead of asking for removing it from this package manager. Furthermore, the excuse of centralization for download stats purposes is no use in this case unless the software disappears entirely since there are many other pages [Arch Linux AUR](https://aur.archlinux.org/packages/keenwrite-bin), [Softpedia](https://www.softpedia.com/get/Office-tools/Text-editors/KeenWrite.shtml) etc, mirroring/redistributing the software, these behaviors do not break the license of the software and you cannot avoid it as mentioned above. Sir, you may need to change the license of your software if you do care about it.

The manfiest was removed to respect you for building such a great application, but it does not mean we agree with what you expressed.

have a good day.

**Comment by bjansen** [comment]
@DaveJarvis data has been sync from the various scoop buckets, and KeenWrite is no longer listed at https://bjansen.github.io/scoop-apps/
