### ISSUE TITLE
[Bug]: Install emacs 29.1 failed

### ISSUE THREAD

**Issue by dragove** [ScoopInstaller/Extras#11669]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

emacs

### Expected/Current Behaviour

Expected:

install successfully

Current Behaviour:

```powershell
Installing 'emacs' (29.1) [64bit] from extras bucket
Loading emacs-29.1.zip from cache
Checking hash of emacs-29.1.zip ... ok.
Extracting emacs-29.1.zip ... Could not find 'emacs-29.1'! (error 16)
所在位置 C:\Users\jingchun\scoop\apps\scoop\current\lib\core.ps1:638 字符: 9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'emacs-29.1'! (err
   or 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'emacs-29.1'! (error 16)
```

### Steps to Reproduce

```console
scoop update
scoop install emacs
```

### Possible Solution

Seems sth wrong with extraction

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
3360010ed (HEAD -> master, origin/master, origin/HEAD) ungoogled-chromium: Update to version 115.0.5790.110-1.1
```

### Scoop Config

```console
only github token is configured
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ltylty** [comment]
+1

**Comment by cabins** [comment]
have the same error

**Comment by mifuyne** [comment]
The manifest was written to expect a `emacs-29.1` folder inside the zip. However, this version wasn't packed that way. The zip opens right to the root of the emacs install, rather than storing them all into a emacs-29.1 folder.

A temporary workaround is to find the emacs manifest and remove the `extract_dir` line (line 13). And hope that the next version will include a folder next time.

Just be aware that scoop will say something about uncommitted changes if you don't revert the removal before the next update.

Hope that helps!
