### ISSUE TITLE
whatsapp Non-functional outdated

### ISSUE THREAD

**Issue by isazajuancarlos** [ScoopInstaller/Extras#11698]
![image](https://github.com/ScoopInstaller/Extras/assets/54165021/b28e6901-582e-4d46-86d9-e5840bdd42ba)

**Comment by HUMORCE** [comment]
The version `2.2326.10` is the latest version of whatsapp announced. it has built-in auto updates and hot updates, it will be consistent with its web client, normally.

I am not aware of any solution to the problem you reported, for type of the program, use its official installation instead. (e.g. [msstore](https://apps.microsoft.com/store/detail/whatsapp/9NKSQGP7F2NH))

**Comment by EstebanMunoz** [comment]
For some reason, the last stable release published in the whatsapp releases page, is not actually their last release. The version of the app donwloaded from the MS Store is the `2.2331.4.0`, while the last published release is the `2.2326.10`. Since the later is not the latest version, the app is in fact outdated and unusable. I guess the only way to get an official downloaded application is through the MS Store at the moment.

**Comment by sasasqt** [comment]
can we change the source url to the mircosoft one?
here is a online tool to get the download link from ms store:
https://store.rg-adguard.net/
![image](https://github.com/ScoopInstaller/Extras/assets/56587914/b35d521b-8ee1-446e-8035-a7bd4c002310)
 
[Retail (final version), RP (Release Preview – preview of the final version), Slow (Windows Insider Slow Ring) or Fast (Windows Insider Fast Ring)]

**Comment by Pixelartist** [comment]
Hello fellow travelers,

I had the same issue - and am waiting for the "hotfix" to be applied. This takes age - and eventually fails with some error.
![image](https://github.com/ScoopInstaller/Extras/assets/2902678/d6477c6a-cb01-4ba2-b49b-c795951a05ec)
I would support @sasasqt request to reroute to the MS store version.

**Comment by Oddly** [comment]
I've got the same issue @Pixelartist is experiencing.
