### ISSUE TITLE
psiphon3@183: hash check failed

### ISSUE THREAD

**Issue by GuiReboucas** [ScoopInstaller/Extras#13203]

**Comment by aliesbelik** [comment]
Already fixed as #13204.

**Comment by GuiReboucas** [comment]
> Already fixed as #13204.
it still gives out an error

**Comment by aliesbelik** [comment]
Not still but again. :shrug:

Scoop tracks only major version of psiphon (`ClientVersion` change, `183` at the moment) and uses unversioned link to download the binary (`https://psiphon.ca/psiphon3.exe`), so any minor update (`ClientBuild` change, e.g. `183.20240504123908`) will happen unnoticed by scoop and lead to hash check failure on attempt to download/install.
These cases are usually handled automatically by bot if the issue like this one is raised.

Looks like another minor update took place since #13203/#13204 have been raised, already handled as #13238.

I guess it could be annoying but seems the is at the moment no easy way to track full version changes for psiphon to perform autoupdate properly and at the time.

**Comment by GuiReboucas** [comment]
Damn that's unfortunate
