### ISSUE TITLE
supermium@122.0.6261.152: hash check failed

### ISSUE THREAD

**Issue by quardbreak** [ScoopInstaller/Extras#13225]
```
> scoop install extras/supermium
Installing 'supermium' (122.0.6261.152) [64bit] from 'extras' bucket
supermium_122_64_setup.exe (103.9 MB) [=======================================================================] 100%
Checking hash of supermium_122_64_setup.exe ... ERROR Hash check failed!
App:         extras/supermium
URL:         https://win32subsystem.live/supermium/downloads/supermium_122_64_setup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    8c500966b7c644dbf40f57c8cc9fd14a60a2acdaf4c5f05425eafe7cc8f9c053
Actual:      ddf7a41ee3444cb32c141a60844d2f0ee7c3fdcf8f8be015328d9b0582400752
```

**Comment by bt4ibwem8** [comment]
should be re-opened, the correct hash is:
3bd306b6bc1bae4a603b7be777ccf159c8de86ceac98e32cc37d7766545f0f88

**Comment by bt4ibwem8** [comment]
Expected:    3bd306b6bc1bae4a603b7be777ccf159c8de86ceac98e32cc37d7766545f0f88
Actual:      88cadd4496444da50c756c52b1ac439a115b6026f78ee87bf35b7e549d5607d8

**Comment by aliesbelik** [comment]
@bt4ibwem8 Please raise next time new issue in form that scoop suggest in case of hash check failure
```
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=supermium%40122.0.6261.152%3a+hash+check+failed
```
instead of commenting to the closed issue.
In that case bot will check and resolve the issue automatically (like this one above) that seems to be a bit more productive than waiting for maintainer's reaction.

Looks like [122.0.6261.152 (R4)](https://github.com/win32ss/supermium/releases/tag/v122-r4) was silently hotfixed, which couldn't be detected by scoop, and [122.0.6261.152 (R5)](https://github.com/win32ss/supermium/releases/tag/v122-r5) uses the same version. I wonder if we could/should add "release" part to version, since naming strategy looks still quite unstable.
