### ISSUE TITLE
Calibre: installing older versions support

### ISSUE THREAD

**Issue by aj0413** [ScoopInstaller/Extras#3781]
Hi,

Seems the fosshub url can't be used by scoop to generate a valid url for downloading older versions as the app manifest is currently written.

Would suggest changing the download url:

https://download.calibre-ebook.com/$version/calibre-portable-installer-$version.exe

I created a local version of the manifest with this change today when I realized the new version wouldn't work due to file path being too long

**Comment by Dabombber** [comment]
I think

https://www.fosshub.com/Calibre-old.html/calibre-portable-installer-$version.exe

would work for previous and current versions, although someone more familiar with fosshub might know of some disadvantage to using `-old.html` instead of `.html`. If there's none then this might apply to all fosshub downloads.

**Comment by aj0413** [comment]
That looks promising as well.

Any reason to stick to the fosshub version instead of through the owned domain, though?

Just seems simpler, honestly. Glad to know that this might help improve other manifests, though
