### ISSUE TITLE
Playnite persist

### ISSUE THREAD

**Issue by Skyline404** [ScoopInstaller/Extras#4919]
Please add Themes and Extensions as persisted folders.
Also: 
`C:\Users\<username>\scoop\apps\playnite\current\Backup\exclusionList.json`
`C:\Users\<username>\scoop\apps\playnite\current\Backup\windowPositions.json`

Maybe all files from backup folder ?

**Comment by Lockszmith** [comment]
Per rejected PR https://github.com/lukesampson/scoop-extras/pull/5088...

I think the problem is that the Themes folder is part of the downloaded package, so if it is persisted, the unpacking will override anything in Themes.
This is the problem with applications that are not really designed to be portable.

Any way to persist specific subfolders (with unknown names) and a single file?
