### ISSUE TITLE
ungoogled-chromium crashes on everypage

### ISSUE THREAD

**Issue by hronro** [ScoopInstaller/Extras#5479]
ungoogled-chromium version: 87.0.4280.67-1

https://user-images.githubusercontent.com/15059605/103122329-b6394500-46ba-11eb-8ef2-7edc41a102e6.mp4

**Comment by foisonocean** [comment]
Hi @Ash258, I just notice you have upgraded `ungoogled-chromium` in 86fe373ec84c4b0197925ab9a34707e3b8319689.

Does ungoogled-chromium works for your? I install `87.0.4280.67-1` and `87.0.4280.141-1` via scoop, neither of them works.

Downloading zip from https://github.com/tangalbert919/ungoogled-chromium-binaries/releases directly works for me thought.

**Comment by pdeak** [comment]
Yea, this still doesn't work for me either, crash on every page.

**Comment by 1hiking** [comment]
Can report this also happens to me :/

**Comment by ikenichiro** [comment]
To comment what I know, executing from the "current" directory will crash upon startup.
However, executing within the latest version number directory (e.g. directory "89.0.4389.90-1") will have no problem.
I think it has something to do with the sandbox feature, since you can execute the chrome.exe by using "--no-sanbox" argument within the "current" directory.

Unfortunately I do not have a solution to fix this issue, but I hope this information (and a workaround?) will help people solve this issue.
