### ISSUE TITLE
[Request] update inkscape to v1.1.1

### ISSUE THREAD

**Issue by azawawi** [ScoopInstaller/Extras#6912]
Could you please update inkscape to 1.1.1?
I noticed that the 32-bit 7z builds are not there anymore.

https://inkscape.org/release/1.1.1/platforms/

**Comment by rashil2000** [comment]
Please make a PR!

**Comment by tech189** [comment]
Autoupdate will not work for Inkscape anymore because they have added the commit to the filename. Same problem as https://github.com/ScoopInstaller/Versions/issues/284#issuecomment-979545915. Both use gitlab for CI to make the builds but the download page is separate from the releases page, so it's impossible to use checkver 😢

It would be great if autoupdate could follow a link to its destination. E.g., checkver could be set up to look for `Inkscape\s+([\d.]+)` on https://inkscape.org/release and then it could generate the `$version` link to follow such as https://inkscape.org/release/inkscape-$version/windows/64-bit/compressed-7z/dl/ which in turn could be scanned for the link using regex `please\s<a href="(.+)"` to get the file https://inkscape.org/gallery/item/29349/inkscape-1.1.1_2021-09-20_3bf5ae0d25-x64.7z.

For comparison, Homebrew has this feature https://github.com/Homebrew/homebrew-cask/blob/cca22db6636ffa378621ff9c610c7bb32a7c44d2/Casks/geogebra.rb#L12 and Chocolatey uses `Get-RedirectedUrl` in their script: https://github.com/chocolatey-community/chocolatey-packages/blob/726889ecfafacc99275f89a3872ef0d08f7ad541/automatic/inkscape/update.ps1#L34.

But this would require a lot of work done to get something working. Temporarily, I could set up a php script on my website to get the filename but it seems out of place for scoop autoupdate to rely on an external source. Maybe we could set up a custom github actions script for tricky sites like these? Because such a common app as inkscape should have autoupdate working.

**Comment by rashil2000** [comment]
The checkver property supports the `script` field, which means you can directly run PowerShell commands to fetch anything required.

So it's possible to write a small PowerShell script and run it in checkver.

**Comment by tech189** [comment]
Oh perfect! I must have missed that in the wiki. I found an example in https://github.com/ScoopInstaller/Java/blob/2e09deae7f1565ea57065ca66ce742d0d93e4549/bucket/oraclejre8.json so I'll try making a PR 😀

**Comment by tech189** [comment]
I need a little bit of help, when running `checkver` on the following manifest, I get this error:
```
inkscape: 1.1.1 (scoop version is 1.1) autoupdate available                
Forcing autoupdate!
Autoupdating inkscape
DEBUG[1640260715] [$updatedProperties] = [url hash] -> C:\Users\me\scoop\apps\scoop\current\lib\autoupdate.ps1:446:5
ERROR Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be determined."
```

I looked up the line which is failing but I don't really know much powershell and I couldn't see any reference to `.ctor`

When running the script I added to the manifest, I get the desired urls and version:
```
1.1.1
https://inkscape.org/gallery/item/29417/InkscapePortable_1.1.1.paf.exe     
https://inkscape.org/gallery/item/29349/inkscape-1.1.1_2021-09-20_3bf5ae0d25-x64.7z
```

<details>
<summary>Manifest</summary>
```
{
    "version": "1.1",
    "description": "Professional vector graphics editor",
    "homepage": "https://inkscape.org",
    "license": "GPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://media.inkscape.org/dl/resources/file/inkscape-1.1-x64.7z",
            "hash": "0538bc76fb962c7aa99f2f757dfc0bf3eee986e06ec73605e8a62750e3e2ccd2"
        },
        "32bit": {
            "url": "https://media.inkscape.org/dl/resources/file/inkscape-1.1-x86.7z",
            "hash": "22ca6feb4f2c130663fd79a5edd7ca8412b9628fa31ab8bef11b68dd85ebcacc"
        }
    },
    "extract_dir": "inkscape",
    "bin": [
        "bin\\inkscape.com",
        "bin\\inkview.com"
    ],
    "shortcuts": [
        [
            "bin\\inkscape.exe",
            "Inkscape"
        ]
    ],
    "checkver": {
        "url": "https://inkscape.org/release",
        "script": [
            "$redirUrl = [System.Net.HttpWebRequest]::Create('https://inkscape.org/release').GetResponse().ResponseUri.AbsoluteUri",
            "$version = $redirUrl -split '\\/(inkscape-)?' | Select-Object -last 1 -skip 1",
            "$32bit_dl = Invoke-WebRequest ($redirUrl + '/windows/32-bit/portable-app/dl/') -UseBasicParsing",
            "$64bit_dl = Invoke-WebRequest ($redirUrl + '/windows/64-bit/compressed-7z/dl/') -UseBasicParsing",
            "$32bit_url = 'https://inkscape.org' + ($32bit_dl.links | Where-Object href -match '\\.exe$' | Select-Object -first 1 -expand href)",
            "$64bit_url = 'https://inkscape.org' + ($64bit_dl.links | Where-Object href -match '\\.7z$' | Select-Object -first 1 -expand href)",
            "Write-Output $version $32bit_url $64bit_url"
        ],
        "regex": "(?<version>[\\d.]+)\\s(?<win32biturl>.+)\\s(?<win64biturl>.+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "$matchWin64BitUrl"
            },
            "32bit": {
                "url": "$matchWin32BitUrl"
            }
        }
    }
}
```
</details>

**Comment by LazyGeniusMan** [comment]
@tech189 change the autoupdate url to
```
"autoupdate": {
        "architecture": {
            "64bit": {
                "url": "$matchWin64biturl"
            },
            "32bit": {
                "url": "$matchWin32biturl"
            }
        }
    }
```
Dont use capitalize `B` and `U`

it should work
![image](https://user-images.githubusercontent.com/58850480/147247707-c3ffc477-7028-4d6c-82ca-5ba8788d8031.png)

**Comment by tech189** [comment]
Thanks for the help! I made the PR 🚀
