### ISSUE TITLE
(Request) add Microsoft-Teams

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7157]
PackageIdentifier: Microsoft-Teams
PackageVersion: 1.4
PackageLocale: en-US
Publisher: Microsoft
PackageName: Microsoft Teams
License: proprietary
ShortDescription: Meeting app by Microsoft
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.16575/Teams_windows_x64.exe-
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by Brawl345** [comment]
See #3595
Someone already made a manifest for it but did not make a PR (@FriendlyNeighborhoodShane still interested?)

**Comment by rashil2000** [comment]
Duplicate

**Comment by FriendlyNeighborhoodShane** [comment]
I no longer use Teams for the moment. I could still create the PR if y'all would prefer, but someone else probably still needs to volunteer as an active maintainer so... 

The maintainance burden probably won't be much, checkver is set up for it.

Also for anyone else making a PR: you might wanna use the raw script (like the `scripts/pyshim.ps1` already in this repo), instead of inlining it in the JSON like I did (which looks ungly and unmaintainable).
