### ISSUE TITLE
Update discord version

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#8051]
The discord version we are using from scoop is very very old.
discord now don't update nupkg so either we will have have extract DiscordSetup.exe or use https://github.com/portapps/discord-portable . I think we should use https://github.com/portapps/discord-portable because its portable and stores data in scoop\apps\discord\data folder instead %appdata%\discord (the electron shit) and also its [configurable](https://portapps.io/doc/configuration/)

**Comment by rashil2000** [comment]
Where can we see what is the latest version of discord?

The portapps build is also very old it seems

**Comment by SonaliBendre** [comment]
not possible as https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86 doesn't show version

**Comment by SonaliBendre** [comment]
oh wait 
this url https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9004/DiscordSetup.exe

**Comment by SonaliBendre** [comment]
we just have to extract exe file to get nupkg file

**Comment by rashil2000** [comment]
Where did you get the url?

**Comment by HUMORCE** [comment]
> not possible as https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86 doesn't show version

> oh wait
this url https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9004/DiscordSetup.exe

i have tried this, its built-in updater blows everything up.

**Comment by rashil2000** [comment]
discord.json was recently updated to include a script for disabling automatic updates

**Comment by SonaliBendre** [comment]
> discord.json was recently updated to include a script for disabling automatic updates

it doesn't work correctly

**Comment by rashil2000** [comment]
What is the error?

/cc @MathewBlock

**Comment by ShadowCreator250** [comment]
Yes, I also noticed this.

Discord checks its updates on startup. It has to get the new versions from somewhere. 
I suspect it does that per module. I looked at the installer log while trying to figure exactly that out and it seemed like it makes a POST to some route. I'm currently not on my PC else I would copy that in this comment.

I wish we could force electron to start the network traffic recording on startup instead of manually in the developer console.
Another possibility could be forcing Discord to use http instead of https and using a VM or some proxy to record the traffic.

**Comment by MathewBlock** [comment]
I've managed to get the checkver stuff working again and the download pointing at the new files, however now I believe I experience the issue @SonaliBendre describes.

`Error: Cannot find module 'discord_desktop_core'`

Bringing back the auto-updater avoids this issue, but that doesn't feel like a good solution. I've seen other providers such as https://github.com/portapps/discord-portable are now up-to-date and they use a method involving `USE_PINNED_UPDATE_MANIFEST` and a `pinned_update.json`. I haven't done enough research yet to understand this and whether we can do a similar solution.

Pointing our download towards the non-affiliated discord-portable as @SonaliBendre suggests is potentially a solution but I feel that is more a question for the moderators since it's a matter of policy. Personally I think we should point directly at official sources but I accept we don't have a workable solution yet.

**Comment by rashil2000** [comment]
The `brave` manifest uses portapps. If the version is up to date, we can switch to using portapps.
