### ISSUE TITLE
gcloud@380.0.0: decompress error

### ISSUE THREAD

**Issue by FreshKiryl** [ScoopInstaller/Extras#8298]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by issaclin32** [comment]
You can try removing the cached ZIP, and install again to see if it works.
`scoop cache rm *`
`scoop install gcloud`


Extraction works fine on my PC.
```
Installing 'gcloud' (380.0.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1f8739|OK  |   3.4MiB/s|D:/scoop/cache/gcloud#380.0.0#https_dl.google.com_dl_cloudsdk_channels_rapid_downloads_google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip ... ok.
Extracting google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip ... done.
Linking D:\scoop\apps\gcloud\current => D:\scoop\apps\gcloud\380.0.0
Creating shim for 'gcloud'.
Creating shim for 'gsutil'.
Creating shim for 'bq'.
Creating shim for 'docker-credential-gcloud'.
Creating shim for 'git-credential-gcloud'.
'gcloud' (380.0.0) was installed successfully!
```

**Comment by FreshKiryl** [comment]
Installing 'gcloud' (380.0.0) [64bit]
google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip (148,2 MB) [=======================================] 100%
Checking hash of google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip ... ok.
Extracting google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Irina\scoop\apps\gcloud\380.0.0\google-cloud-sdk-380.0.0-windows-x86_64-bundled-python.zip.
Log file:
  ~\scoop\apps\gcloud\380.0.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=gcloud%40380.0.0%3a+decompress+error

**Comment by rashil2000** [comment]
Refer here https://github.com/ScoopInstaller/Scoop/issues/4647

**Comment by issaclin32** [comment]
> Refer here [ScoopInstaller/Scoop#4647](https://github.com/ScoopInstaller/Scoop/issues/4647)

Wow... The case has been reported by users for so many times.
I would suggest adding **7-zip ver19.00** as a helper package as a workaround (such as the case of [extras/scratch](https://github.com/ScoopInstaller/Extras/pull/7388) which uses `extras/winrar-helper`). So that we can avoid the problem even if the user does not have Admin access.

https://github.com/ScoopInstaller/Scoop/issues/4647#issuecomment-1010747119
```
I can't switch to developer mode because... Rights.

(and that's the reason why I use scoop to install things locally to my account)
```

**Comment by rashil2000** [comment]
We could add a manifest `7zip19.00` in the Versions bucket, which will work as intended.

**Comment by issaclin32** [comment]
> We could add a manifest `7zip19.00` in the Versions bucket, which will work as intended.

It is slightly different.

My thoughts on the "helper package" is that is will create a shim called `7z-19.00-helper.exe`, so that it will not affect existing installations of *7-zip*.

Also, I think the best place to put it is in the *Main* bucket, so that users will not have to add *Versions* bucket before they install **GCloud**.
