### ISSUE TITLE
[Request] SignalPortable

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#8647]
Package Request Information
Name: SignalPortable

Description: signal application without install app and trigger UAC

Homepage: https://github.com/portapps/signal-portable

Download link(s): https://github.com/portapps/signal-portable/releases/download/5.38.0-7/signal-portable-win64-5.38.0-7-setup.exe

**Comment by issaclin32** [comment]
I don't think this package is needed.
We already have [extras/signal](https://github.com/ScoopInstaller/Extras/blob/master/bucket/signal.json) in the bucket, and it can totally install and run **without admin rights**, because *Scoop* extracts the installer instead of executing it.

Also, using official release is better because *portapps* need time to handle new versions.  (official release is **ver 5.45.1** currently)

**Comment by issaclin32** [comment]
@sterno900 Instead of using *PortableApps*, we could simply create a **junction** that points `$Env:AppData\signal` (or other config folders) to `$dir\config`. Which is easier to maintain , and more transparent to users.

However, as the current rules / guidelines, we will **not** do this in official buckets due to extra maintainence labor / potential to have new problems when an app updates. Our team have discussed about this issue for several times, and we decided not to do that, at least for now.

Another problem is that, if we use *PortableApps* as the source, we will lag behind in version updates (compared to using official release) because *PortableApps* need some time to handle it.

By the way, there is an (unofficial) [PortableApps bucket](https://github.com/p8rdev/scoop-portableapps). You can also send an **issue** or **PR** there.
