### ISSUE TITLE
[Bug] AutoIT Script Editor requires VCRedist

### ISSUE THREAD

**Issue by mesmariusz** [ScoopInstaller/Extras#8650]
Hi 

One sciTE (AoutIT Script Editor) installed via 

https://scoop.sh/#/apps?q=autoit&s=0&d=1&o=true

cant run in Windows11

because of missing vcredist

https://www.autoitscript.com/trac/autoit/ticket/3798#comment:12

https://www.autoitscript.com/forum/topic/207914-i-cant-open-sciteexe/

After manual installation of all three vcredist, it works.

Probably someone should improove autoit installlation script for AutoIT

**Comment by issaclin32** [comment]
AutoIt is a fairly popular app, but no one reported this issue before.

I assume this is an **upstream** problem. That is, *AutoIt* used to have those required DLLs bundled, but they removed them in latest versions.

I just [added those VCRedist packages to suggest](https://github.com/ScoopInstaller/Main/commit/a0e73654bdb8045c611d170c853ffcb6d56d6859), so that at least users have hint on how to fix the missing DLLs.
