### ISSUE TITLE
notepadplusplus has no Plugin Admin in Plugins menu

### ISSUE THREAD

**Issue by Mosney** [ScoopInstaller/Extras#8748]
## Bug Report

**Package Name:** [name of package which has bug(s)]

 notepadplusplus
### Current Behaviour
Has no "Plugin Admin" in Menu-Plugins

### Expected Behaviour
I believe this thing was here before, an plugin manager named "Plugin Admin".

### Additional context/output
I uninstall notepadpkuspkus then install again, still no progress.

### Possible Solution

I install from official installer and then copy its \plugins\Config\nppPluginList.dll to scoop version, solved.
### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 11 22000.739
**OS architecture:** [e.g. 32bit, 64bit]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.5
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-06-23T00:23:15.1038498+08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "alias": {}
}
```

**Comment by issaclin32** [comment]
*Scoop* uses the portable ZIP version of Notepad++ for installation. (https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.2/npp.8.4.2.portable.x64.zip)

Since `nppPluginList.dll` exists in the ZIP file, I think it is a bug of **Notepad++** itself.
The best way to solve this is to [report the issue to Notepad++ team](https://github.com/notepad-plus-plus/notepad-plus-plus/issues).

If they didn't respond, or did not want to solve it. Then, we can try to fix it in *Scoop* packages.
(for example, download additional files from Notepad++'s repo, etc.)
