### ISSUE TITLE
Create a Firefox shortcut to startup with Scoop profiles

### ISSUE THREAD

**Issue by lifansama** [ScoopInstaller/Extras#8779]
After I updated Firefox, it switched to the `default-release` profile.
I find I can add an argument to specify the `Scoop` profile like `firefox.exe -P Scoop`.
Is there any way to create a shortcut including the `-P` argument automatically, when we install or update Firefox？
[Firefox/CommandLineOptions](https://wiki.mozilla.org/Firefox/CommandLineOptions#User_profile)

**Comment by HUMORCE** [comment]
> After I updated Firefox, it switched to the default-release profile.

that's why we set notes for the manifest.

> I find I can add an argument to specify the Scoop profile like firefox.exe -P Scoop.

the manifest used this launch option a long time ago, it has led to a number of problems.

> For pre_install, we could probably open $Env:AppData\Mozilla\Firefox\profiles.ini, and set the "Scoop profile" as default. (put Default=1 under it), but I am not sure if there is any potential problem if we do this.

**firefox cannot share profiles between individual installations.**
```
<SCOOP>\apps\firefox\100.0
<SCOOP>\apps\firefox\102.0
```
each firefox update via scoop is done as a individual installation, so `profiles.ini` will be ignored. even if this method were possible, this would change the last profile(default) selected by users.

**Comment by issaclin32** [comment]
Closing the issue because it is considered settled.
Feel free to **comment** / **open a new issue** if needed.
