### ISSUE TITLE
[Request] gtk#

### ISSUE THREAD

**Issue by rihaq** [ScoopInstaller/Extras#8972]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** [name of new package]
Gtk#
**Description:** [clear and concise details of what it is]
Gtk# is a Graphical User Interface Toolkit for mono and .Net
**Homepage:** [a URL/link]
https://www.mono-project.com/gtksharp
**Download link(s):** [URL(s)/link(s)]
https://xamarin.azureedge.net/GTKforWindows/Windows/gtk-sharp-2.12.45.msi
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

406

**Comment by rihaq** [comment]
Its actually not. Its a pure CLI library

**Comment by issaclin32** [comment]
To my understanding, this is neither a GUI tool nor a *"simple"* command-line tool.

It is a **runtime library**, just like [VCRedist](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist2022.json) or [Windows Desktop Runtime](windowsdesktop-runtime-lts).

I think we should add this to *Extras* bucket, and run the MSI installer in `pre_install`. (instead of extracting it)

----

[sandbox record (brief)](https://github.com/ScoopInstaller/Extras/files/9333334/sandbox-tree.txt)

[sandbox record (full)](https://github.com/ScoopInstaller/Extras/files/9333335/sandbox-tree-full.txt)
