### ISSUE TITLE
[Request] ContextMenuForWindows11

### ISSUE THREAD

**Issue by sayeed205** [ScoopInstaller/Extras#9274]
### Information

**Name:** ContextMenuForWindows11

**Description:** Add Custom Context Menu For Windows11

**Homepage:** https://github.com/ikas-mc/ContextMenuForWindows11

**Download link(s):** https://github.com/ikas-mc/ContextMenuForWindows11/releases

**Some indication of popularity/repute:** 530+ Stars and 25+ Forks

**Comment by KrisSchneider** [comment]
This seems to be a UWP app which scoop does not support. When it comes to UWP apps like this, it's much better to install it via the [MS Store](https://www.microsoft.com/store/productId/9PC7BZZ28G0X). BTW the free trial is forever, it's not required to buy the item. However, if are feeling generous, buying the app supports funding of the app to the developer.

I tried making it into a portable app, but due to the nature of UWP apps, I had no success. Sorry @sayeed205 if this causes any issues.

**Comment by sayeed205** [comment]
No issues at all. Thanks for trying though @KrisSchneider . Okay then I am closing this issue.
