### ISSUE TITLE
[Bug] Brave does not always use `--user-data-dir`

### ISSUE THREAD

**Issue by BlackPowerade** [ScoopInstaller/Extras#9548]
## Bug Report

**Package Name:** `brave`

### Current Behavior

Brave does not respect its installation context when set as the default browser. Leading to differing configurations when launched via different contexts (Start Menu/Pinned Icon in taskbar/`brave` command/Open with...)

### Expected Behavior

Brave uses the same User Data directory regardless of its launch context unless otherwise specified. `--user-data-dir`

### Possible Solution

1. Include a `post_install` like     
`New-Item -ItemType Junction -Path "$env:AppData/../Local/BraveSoftware/Brave-Browser/User Data" -Target "$persist_dir/brave/User Data"`   
Downside: requires elevated prompt or `depends: sudo`   
2. Include the `post_install` as an optional extra to be run by the user after install (like some of the context menu .reg files)
Downside: again, requires elevation. But, this is only run if the user wishes.     
3. Get down and dirty with the registry, including a .reg file to fix the file and protocol associations.
Downside: would be a massive PITA.     
4. Hit up the brave developers, see if they would take the reigns on this?

### System details

**Windows version:**     
Microsoft Windows 10 IoT Enterprise LTSC 19044

**OS architecture:**     
64

**PowerShell version:**   
7.2.6

#### Scoop Configuration

```json
{
  "last_update": "2022-10-20T19:02:10.7870260+03:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}

```

**Comment by HUMORCE** [comment]
all browsers have this problem when specifying a profile location.

**Comment by BlackPowerade** [comment]
I see. I'll just close this then.

**Comment by HUMORCE** [comment]
I did not mean for you to close this issue, it's something worth discusing

**Comment by dionysius** [comment]
I would reopen this issue as well. I ran down a rabbit hole to figure out with "Open with ..." in Brave does not load my profile as well as several other locations.

I figured out, and it is how OP stated, brave.exe **needs** `--user-data-dir`. My observation is, if by any means brave is started without it, it spawns a new instance and uses/creates `%appdata%/...` as profile. This can also be observed in the taskbar, it will have its own new icon in the list of open/pinned applications. The user is now confused, which icon to pin to the taskbar.

We should try to figure out that brave never ever tries to use the profile in AppData. The scoop installer script already takes care of copying the full folder from there if one exists. The installer also writes a start menu entry for Brave in `Scoop Apps` with the correct `--user-data-dir` argument. This seems to be the only place where it is defined. If someone opens brave from there or has pulled the icon from there to the taskbar, everything is fine.

One immediate problem occurs if someone tries to make brave as default browser via the brave settings. It will offer itself as selection for Browser in Default Apps, but the entry seems to be missing the `--user-data-dir`. If someone now opens a link from any external program, it will start brave without this option and thus creating a separate instance. Does somebody know what all exactly happens during this "Make brave as default browser" button in the brave settings?

I was able to fix it with help of `filetypesman` from the `nirsoft` bucket ([project homepage](https://www.nirsoft.net/utils/file_types_manager.html)), but I also needed a file-type helper `.html` to assign `Open with ...` with the brave browser entry as it seems I couldn't find the exact place where this Default Apps list for Browsers comes from. The reason of using this tool instead of the Windows Settings integrated one, was, it allowed the command to be edited so I could pass `--user-data-dir`:
![image](https://user-images.githubusercontent.com/1341084/199359491-6293270c-14f6-45dd-a026-308998621c19.png)

Changing the command was only needed once, as it seems this relation is mapped to `User Choice` which in my case is called `BraveHTML.SASV...`:
![image](https://user-images.githubusercontent.com/1341084/199359817-7ed75c5e-0a2d-443a-ad68-fc0009395b29.png)

This seems to also have automatically fixed the `Default Apps` Browser selection (please can someone try to confirm this).

The problem now is: A fresh scoop brave install wont have any entries for brave in the registry (which generally IMO is kinda a good behaviour). So the installers hands are tied for this. But the installer could try to already create a `User Choice`, so when someone tries to "Open with ..." something, brave is already there in the list.

The problem goes also a bit further. Once anyone has happened to have such a broken profile in AppData, a complete uninstall and install of brave would copy the broken profile to scoop persist (can someone check if it is overwriting it?). I was happy that I made from both locations a backup before, since at that time I was not sure which one was the one I want to keep.

**Comment by bGZo** [comment]
Hello, I meet this issue as well. Refer to the first of OP's possible solutions:

> New-Item -ItemType Junction -Path "$env:AppData/../Local/BraveSoftware/Brave-Browser/User Data" -Target "$persist_dir/brave/User Data"

They don't need admin privilege(`sudo`)😂,  junction link also used in Scoop via: https://github.com/ScoopInstaller/Scoop/blob/8aee6f99803d0f0aeab252e1d9d4848777185c51/lib/install.ps1#L1254-L1261C2.

Compared to modify `regedit` or something else, I would like to use junction link to deal with that.

**Comment by dionysius** [comment]
What is scoops strategy in general, does it want to allow an application be installed via scoop **and** on classic system way (without interference between those)?

If No, i'd support the junction. If Yes, we need to be careful if we really want to do a junction since both would use the same profile.
