### ISSUE TITLE
[Request]  Patch My PC

### ISSUE THREAD

**Issue by anderlli0053-storage** [ScoopInstaller/Extras#9691]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Patch My PC

**Description:** Free, easy-to-use program that keeps over 300 applications up-to-date on your computer. It is an easy way to update or install a large list of programs on to your computer.

**Homepage:** https://patchmypc.com/

**Download link(s):** https://patchmypc.com/freeupdater/PatchMyPC.exe

**Some indication of popularity/repute:** https://patchmypc.com/customer-testimonials

**Comment by Zliced13** [comment]
@anderlli0053-storage please read https://github.com/ScoopInstaller/Extras/issues/8596

**Comment by anderlli0053** [comment]
@Zliced13  Thanks, but still i don't understand, at least i think that i do not..  Because the software detects other software via registry and cannot properly check for updates for them, when they are installed via Scoop and bypassed the registry, then i assume the PatchMyPc will not be added? Not even in 3rd party bucket(s) ?

**Comment by Zliced13** [comment]
You can add it to your own bucket, it just won't be added to official buckets?

**Comment by anderlli0053** [comment]
Ah ok, thank you though

**Comment by anderlli0053** [comment]
Will close this on the other acc
